#!/bin/bash

#bspc monitor -d I II III IV V VI VII VIII IX X
if [[ $(hostname) == *"laptop"* ]]; then
bspc monitor HDMI-0 -d I II III IV V
bspc monitor LVDS-0 -d VI VII VIII IX X
else
bspc monitor HDMI-0 -d I II III IV V
bspc monitor DP-0 -d VI VII VIII IX X
fi

bspc config border_width        3
bspc config window_gap          15

bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color "#6e6a86"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a lxappearance state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a blueman-manager state=floating

sxhkd &
picom &
if [[ $(hostname) == *"laptop"* ]]; then
	#xrandr --output HDMI-0 --scale 1x1 --primary --left-of LVDS-0  --output LVDS-0 --dpi 141
	xrandr --output HDMI-0 --scale 1x1 --primary --left-of LVDS-0  --output LVDS-0 --dpi 92
else
	xrandr --output HDMI-0 --mode 1920x1080 --pos 0x0 --rotate normal --left-of DP-0 --output  DP-0 --mode 1440x900 --pos 1920x0 --rotate normal --output DVI-D-0  --off
fi
blueman-applet &
setxkbmap us,th -option grp:caps_toggle,grp_led:scroll
polybar -r -c /home/$USER/.config/polybar/config top &
feh --bg-max /home/$USER/Pictures/wallpaper.jpg
