#! /bin/sh

#bspc monitor -d I II III IV V VI VII VIII IX X
if [[ $HOST == *"laptop"* ]]; then
	bspc monitor HDMI-0 -d I II III IV V
	bspc monitor LVDS-0 -d VI VII VIII IX X
else
	bspc monitor HDMI-0 -d I II III IV V
	bspc monitor DP-0 -d VI VII VIII IX X
fi

bspc config border_width        3
bspc config window_gap          15

bspc config active_border_color '#FF6C11'
bspc config normal_border_color '#2DE2E6'
bspc config focused_border_color '#FF3864'
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a lxappearance state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a blueman-manager state=floating

sxhkd &
picom &
if [[ $HOST == *"laptop"* ]]; then
	xrandr --output HDMI-0 --scale 1x1 --primary --left-of LVDS-0
else
	xrandr --output HDMI-0 --primary  --right-of DP-0
fi 
blueman-applet &
setxkbmap us,th -option grp:win_space_toggle,grp_led:scroll
polybar -r -c /home/$USER/.config/polybar/config top &
feh --bg-max /home/$USER/Pictures/wallpaper.jpg
